:construction_worker: Update CI/CD for liquidator builds
hubbleprotocol/liquidator pull request #1
Opened 2022-10-26 16:27 UTC by andreihrs

2022-10-26 16:41 UTC, peroxy requested changes

2022-10-26 16:41 UTC, peroxy commented on package.json
>      "@switchboard-xyz/switchboard-api": "^0.2.160",
This should be a dev dependency, no need to have this installed in the final image

2022-10-26 16:41 UTC, peroxy commented on Dockerfile
> +CMD ["npm", "run", "start-dev"]
This way we’ll need 2 separate docker images, it would be nicer to have 1 image and you add env variable that specifies if its devnet or mainnet

2022-10-26 17:47 UTC, andreihrs commented on package.json
>      "@switchboard-xyz/switchboard-api": "^0.2.160",
good catch, I was under the impression I added it there

2022-10-27 10:02 UTC, peroxy approved these changes
LGTM - talked about the dockerfile with Andrei

2022-10-27 10:03 UTC, merged